//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsVerification.Web.Repositories.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReportsVertification : DbContext
    {
        public ReportsVertification()
            : base("name=ReportsVertification")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Deduction> Deductions { get; set; }
        public virtual DbSet<Mode> Modes { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Mrot> Mrots { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<WrongReport> WrongReports { get; set; }
    }
}
