//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsVerification.Web.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deduction
    {
        public System.Guid Id { get; set; }
        public System.Guid RegionId { get; set; }
        public decimal FirstQuarter { get; set; }
        public decimal SecondQuarder { get; set; }
        public decimal ThirdQuarter { get; set; }
        public decimal FourthQuarter { get; set; }
        public System.DateTime BeginDate { get; set; }
    
        public virtual Region Region { get; set; }
    }
}
