//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsVerification.Web.Repositories.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public System.Guid Id { get; set; }
        public int UserId { get; set; }
        public Nullable<System.Guid> RegionId { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public Nullable<System.Guid> ModeId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Mode Mode { get; set; }
        public virtual Region Region { get; set; }
    }
}
