 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable once CheckNamespace
namespace ReportsVerification.Web.DataObjects.Enums
{
	/// <summary>
    /// Справочник категорий пользователя
    /// </summary>
	public enum Categories
	{
		/// <summary>
		/// ООО – работодатель
		/// </summary>
		OooEmployer,

		/// <summary>
		/// АО  ? работодатель
		/// </summary>
		AoEmployer,

		/// <summary>
		/// ИП без сотрудников
		/// </summary>
		IpWithoutEmployees,

		/// <summary>
		/// ИП – работодатель
		/// </summary>
		IpEmployer,

		/// <summary>
		/// АО без сотрудников
		/// </summary>
		AoWithoutEmployees,

		/// <summary>
		/// ООО без сотрудников
		/// </summary>
		OooWithoutEmployees,

	}  

	/// <summary>
    /// Справочник режимов пользователя
    /// </summary>
	public enum UserModes
	{
        /// <summary>
        /// ЕНВД
        /// </summary>
        ENVD,

        /// <summary>
        /// УСН
        /// </summary>
        USN,

        /// <summary>
        /// ОСНО
        /// </summary>
        OSNO,

        /// <summary>
        /// ЕСХН
        /// </summary>
        ESHN,

        /// <summary>
        /// ОСНО + ЕНВД
        /// </summary>
        OSNOvsENVD,

        /// <summary>
        /// УСН + ЕНВД
        /// </summary>
        USNvsENVD
    }
}
 
