 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable once CheckNamespace
namespace ReportsVerification.Web.DataObjects.Enums
{
	/// <summary>
    /// Справочник категорий пользователя
    /// </summary>
	public enum Categories
	{
		/// <summary>
		/// ООО – работодатель
		/// </summary>
		OooEmployer,

		/// <summary>
		/// АО  ? работодатель
		/// </summary>
		AoEmployer,

		/// <summary>
		/// ИП без сотрудников
		/// </summary>
		IpWithoutEmployees,

		/// <summary>
		/// ИП – работодатель
		/// </summary>
		IpEmployer,

		/// <summary>
		/// АО без сотрудников
		/// </summary>
		AoWithoutEmployees,

		/// <summary>
		/// ООО без сотрудников
		/// </summary>
		OooWithoutEmployees,

	}  

	/// <summary>
    /// Справочник режимов пользователя
    /// </summary>
	public enum UserModes
	{
		/// <summary>
		/// Патент
		/// </summary>
		Patent,

		/// <summary>
		/// ОСНО
		/// </summary>
		Osno,

		/// <summary>
		/// УСН + ЕНВД
		/// </summary>
		UsnWitnEnvd,

		/// <summary>
		/// ЕСХН + ЕНВД
		/// </summary>
		EshnWithEnvd,

		/// <summary>
		/// ОСНО + ЕНВД
		/// </summary>
		OsnoWithEnvd,

		/// <summary>
		/// ЕНВД
		/// </summary>
		Envd,

		/// <summary>
		/// УСН
		/// </summary>
		Usn,

		/// <summary>
		/// ЕСХН
		/// </summary>
		Eshn,

	}
}
 
