// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.1.34438 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>ReportsVerification.Web</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------

using ReportsVerification.Web.DataObjects.Interfaces;

namespace ReportsVerification.Web.DataObjects.Xsd.SzvmStazh
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class ЭДПФР : IXsdReport
    {

        private SignatureType электроннаяПодписьField;

        private ТипСлужебнаяИнформация1 служебнаяИнформацияField;

        private ЭДПФРОДВ1 оДВ1Field;

        private ЭДПФРСЗВСТАЖ сЗВСТАЖField;

        public ЭДПФР()
        {
            this.сЗВСТАЖField = new ЭДПФРСЗВСТАЖ();
            this.оДВ1Field = new ЭДПФРОДВ1();
            this.служебнаяИнформацияField = new ТипСлужебнаяИнформация1();
            this.электроннаяПодписьField = new SignatureType();
        }

        public SignatureType ЭлектроннаяПодпись
        {
            get
            {
                return this.электроннаяПодписьField;
            }
            set
            {
                this.электроннаяПодписьField = value;
            }
        }

        public ТипСлужебнаяИнформация1 СлужебнаяИнформация
        {
            get
            {
                return this.служебнаяИнформацияField;
            }
            set
            {
                this.служебнаяИнформацияField = value;
            }
        }

        public ЭДПФРОДВ1 ОДВ1
        {
            get
            {
                return this.оДВ1Field;
            }
            set
            {
                this.оДВ1Field = value;
            }
        }

        public ЭДПФРСЗВСТАЖ СЗВСТАЖ
        {
            get
            {
                return this.сЗВСТАЖField;
            }
            set
            {
                this.сЗВСТАЖField = value;
            }
        }
    }

    public partial class SignatureType
    {

        private SignedInfoType signedInfoField;

        private SignatureValueType signatureValueField;

        private KeyInfoType keyInfoField;

        private List<ObjectType> objectField;

        private string idField;

        public SignatureType()
        {
            this.objectField = new List<ObjectType>();
            this.keyInfoField = new KeyInfoType();
            this.signatureValueField = new SignatureValueType();
            this.signedInfoField = new SignedInfoType();
        }

        public SignedInfoType SignedInfo
        {
            get
            {
                return this.signedInfoField;
            }
            set
            {
                this.signedInfoField = value;
            }
        }

        public SignatureValueType SignatureValue
        {
            get
            {
                return this.signatureValueField;
            }
            set
            {
                this.signatureValueField = value;
            }
        }

        public KeyInfoType KeyInfo
        {
            get
            {
                return this.keyInfoField;
            }
            set
            {
                this.keyInfoField = value;
            }
        }

        public List<ObjectType> Object
        {
            get
            {
                return this.objectField;
            }
            set
            {
                this.objectField = value;
            }
        }

        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    public partial class SignedInfoType
    {

        private CanonicalizationMethodType canonicalizationMethodField;

        private SignatureMethodType signatureMethodField;

        private List<ReferenceType> referenceField;

        private string idField;

        public SignedInfoType()
        {
            this.referenceField = new List<ReferenceType>();
            this.signatureMethodField = new SignatureMethodType();
            this.canonicalizationMethodField = new CanonicalizationMethodType();
        }

        public CanonicalizationMethodType CanonicalizationMethod
        {
            get
            {
                return this.canonicalizationMethodField;
            }
            set
            {
                this.canonicalizationMethodField = value;
            }
        }

        public SignatureMethodType SignatureMethod
        {
            get
            {
                return this.signatureMethodField;
            }
            set
            {
                this.signatureMethodField = value;
            }
        }

        public List<ReferenceType> Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }

        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    public partial class CanonicalizationMethodType
    {

        private List<System.Xml.XmlNode> anyField;

        private string algorithmField;

        public CanonicalizationMethodType()
        {
            this.anyField = new List<System.Xml.XmlNode>();
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public List<System.Xml.XmlNode> Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        public string Algorithm
        {
            get
            {
                return this.algorithmField;
            }
            set
            {
                this.algorithmField = value;
            }
        }
    }

    public partial class ТипВременнойПериод
    {

        private System.DateTime сField;

        private System.DateTime поField;

        public System.DateTime С
        {
            get
            {
                return this.сField;
            }
            set
            {
                this.сField = value;
            }
        }

        public System.DateTime По
        {
            get
            {
                return this.поField;
            }
            set
            {
                this.поField = value;
            }
        }
    }

    public partial class ТипСтажевыйПериод2017
    {

        private ТипВременнойПериод периодField;

        private List<ТипСтажевыйПериод2017ЛьготныйСтаж> льготныйСтажField;

        public ТипСтажевыйПериод2017()
        {
            this.льготныйСтажField = new List<ТипСтажевыйПериод2017ЛьготныйСтаж>();
            this.периодField = new ТипВременнойПериод();
        }

        public ТипВременнойПериод Период
        {
            get
            {
                return this.периодField;
            }
            set
            {
                this.периодField = value;
            }
        }

        public List<ТипСтажевыйПериод2017ЛьготныйСтаж> ЛьготныйСтаж
        {
            get
            {
                return this.льготныйСтажField;
            }
            set
            {
                this.льготныйСтажField = value;
            }
        }
    }

    public partial class ТипСтажевыйПериод2017ЛьготныйСтаж
    {

        private ТипСтажевыйПериод2017ЛьготныйСтажТУ туField;

        private ТипСтажевыйПериод2017ЛьготныйСтажОУТ оУТField;

        private ТипСтажевыйПериод2017ЛьготныйСтажИС исField;

        private ТипСтажевыйПериод2017ЛьготныйСтажДопСведенияИС допСведенияИСField;

        private bool допСведенияИСFieldSpecified;

        private ТипСтажевыйПериод2017ЛьготныйСтажВЛ влField;

        public ТипСтажевыйПериод2017ЛьготныйСтаж()
        {
            this.влField = new ТипСтажевыйПериод2017ЛьготныйСтажВЛ();
            this.исField = new ТипСтажевыйПериод2017ЛьготныйСтажИС();
            this.оУТField = new ТипСтажевыйПериод2017ЛьготныйСтажОУТ();
            this.туField = new ТипСтажевыйПериод2017ЛьготныйСтажТУ();
        }

        public ТипСтажевыйПериод2017ЛьготныйСтажТУ ТУ
        {
            get
            {
                return this.туField;
            }
            set
            {
                this.туField = value;
            }
        }

        public ТипСтажевыйПериод2017ЛьготныйСтажОУТ ОУТ
        {
            get
            {
                return this.оУТField;
            }
            set
            {
                this.оУТField = value;
            }
        }

        public ТипСтажевыйПериод2017ЛьготныйСтажИС ИС
        {
            get
            {
                return this.исField;
            }
            set
            {
                this.исField = value;
            }
        }

        public ТипСтажевыйПериод2017ЛьготныйСтажДопСведенияИС ДопСведенияИС
        {
            get
            {
                return this.допСведенияИСField;
            }
            set
            {
                this.допСведенияИСField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДопСведенияИСSpecified
        {
            get
            {
                return this.допСведенияИСFieldSpecified;
            }
            set
            {
                this.допСведенияИСFieldSpecified = value;
            }
        }

        public ТипСтажевыйПериод2017ЛьготныйСтажВЛ ВЛ
        {
            get
            {
                return this.влField;
            }
            set
            {
                this.влField = value;
            }
        }
    }

    public partial class ТипСтажевыйПериод2017ЛьготныйСтажТУ
    {

        private ТипСтажевыйПериод2017ЛьготныйСтажТУОснование основаниеField;

        private decimal коэффициентField;

        private bool коэффициентFieldSpecified;

        public ТипСтажевыйПериод2017ЛьготныйСтажТУОснование Основание
        {
            get
            {
                return this.основаниеField;
            }
            set
            {
                this.основаниеField = value;
            }
        }

        public decimal Коэффициент
        {
            get
            {
                return this.коэффициентField;
            }
            set
            {
                this.коэффициентField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool КоэффициентSpecified
        {
            get
            {
                return this.коэффициентFieldSpecified;
            }
            set
            {
                this.коэффициентFieldSpecified = value;
            }
        }
    }

    public enum ТипСтажевыйПериод2017ЛьготныйСтажТУОснование
    {

        /// <remarks/>
        РКС,

        /// <remarks/>
        МКС,

        /// <remarks/>
        РКСМ,

        /// <remarks/>
        МКСР,

        /// <remarks/>
        Ч31,

        /// <remarks/>
        Ч33,

        /// <remarks/>
        Ч34,

        /// <remarks/>
        Ч35,

        /// <remarks/>
        Ч36,

        /// <remarks/>
        СЕЛО,
    }

    public partial class ТипСтажевыйПериод2017ЛьготныйСтажОУТ
    {

        private ТипСтажевыйПериод2017ЛьготныйСтажОУТКод кодField;

        private string позицияСпискаField;

        public ТипСтажевыйПериод2017ЛьготныйСтажОУТКод Код
        {
            get
            {
                return this.кодField;
            }
            set
            {
                this.кодField = value;
            }
        }

        public string ПозицияСписка
        {
            get
            {
                return this.позицияСпискаField;
            }
            set
            {
                this.позицияСпискаField = value;
            }
        }
    }

    public enum ТипСтажевыйПериод2017ЛьготныйСтажОУТКод
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-1")]
        Item271,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-2")]
        Item272,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-3")]
        Item273,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-4")]
        Item274,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-5")]
        Item275,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-6")]
        Item276,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-7")]
        Item277,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-8")]
        Item278,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-9")]
        Item279,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-10")]
        Item2710,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-ОС")]
        Item27ОС,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-ПЖ")]
        Item27ПЖ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("28-СЕВ")]
        Item28СЕВ,
    }

    public partial class ТипСтажевыйПериод2017ЛьготныйСтажИС
    {

        private ТипСтажевыйПериод2017ЛьготныйСтажИСОснование основаниеField;

        private bool основаниеFieldSpecified;

        private object itemField;

        public ТипСтажевыйПериод2017ЛьготныйСтажИСОснование Основание
        {
            get
            {
                return this.основаниеField;
            }
            set
            {
                this.основаниеField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ОснованиеSpecified
        {
            get
            {
                return this.основаниеFieldSpecified;
            }
            set
            {
                this.основаниеFieldSpecified = value;
            }
        }

        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    public enum ТипСтажевыйПериод2017ЛьготныйСтажИСОснование
    {

        /// <remarks/>
        СЕЗОН,

        /// <remarks/>
        ПОЛЕ,

        /// <remarks/>
        УИК104,

        /// <remarks/>
        ВОДОЛАЗ,
    }

    public partial class ТипСтажевыйПериод2017ЛьготныйСтажИСВыработкаВчасах
    {

        private string часыField;

        private string минутыField;

        public string Часы
        {
            get
            {
                return this.часыField;
            }
            set
            {
                this.часыField = value;
            }
        }

        public string Минуты
        {
            get
            {
                return this.минутыField;
            }
            set
            {
                this.минутыField = value;
            }
        }
    }

    public partial class ТипСтажевыйПериод2017ЛьготныйСтажИСВыработкаКалендарная
    {

        private string всеМесяцыField;

        private string всеДниField;

        public string ВсеМесяцы
        {
            get
            {
                return this.всеМесяцыField;
            }
            set
            {
                this.всеМесяцыField = value;
            }
        }

        public string ВсеДни
        {
            get
            {
                return this.всеДниField;
            }
            set
            {
                this.всеДниField = value;
            }
        }
    }

    public enum ТипСтажевыйПериод2017ЛьготныйСтажДопСведенияИС
    {

        /// <remarks/>
        ДЕТИ,

        /// <remarks/>
        ДЕКРЕТ,

        /// <remarks/>
        ДОГОВОР,

        /// <remarks/>
        ДЛОТПУСК,

        /// <remarks/>
        ВАХТА,

        /// <remarks/>
        МЕСЯЦ,

        /// <remarks/>
        КВАЛИФ,

        /// <remarks/>
        ОБЩЕСТ,

        /// <remarks/>
        СДКРОВ,

        /// <remarks/>
        ОТСТРАН,

        /// <remarks/>
        ПРОСТОЙ,

        /// <remarks/>
        УЧОТПУСК,

        /// <remarks/>
        МЕДНЕТРУД,

        /// <remarks/>
        НЕОПЛДОГ,

        /// <remarks/>
        НЕОПЛАВТ,

        /// <remarks/>
        ДОПВЫХ,

        /// <remarks/>
        ЗГДС,

        /// <remarks/>
        ЗГД,

        /// <remarks/>
        ЗГГС,

        /// <remarks/>
        ЗМС,

        /// <remarks/>
        ЗМД,

        /// <remarks/>
        ДЛДЕТИ,

        /// <remarks/>
        ЧАЭС,

        /// <remarks/>
        НЕОПЛ,

        /// <remarks/>
        ДЕТИПРЛ,

        /// <remarks/>
        СЛПРИЗ,

        /// <remarks/>
        ТРУДЛИЦО,

        /// <remarks/>
        ПРОЖСУПР,

        /// <remarks/>
        ПРЗАГР,

        /// <remarks/>
        ВРНЕТРУД,
    }

    public partial class ТипСтажевыйПериод2017ЛьготныйСтажВЛ
    {

        private ТипСтажевыйПериод2017ЛьготныйСтажВЛОснование основаниеField;

        private bool основаниеFieldSpecified;

        private object itemField;

        private decimal доляСтавкиField;

        private bool доляСтавкиFieldSpecified;

        public ТипСтажевыйПериод2017ЛьготныйСтажВЛОснование Основание
        {
            get
            {
                return this.основаниеField;
            }
            set
            {
                this.основаниеField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ОснованиеSpecified
        {
            get
            {
                return this.основаниеFieldSpecified;
            }
            set
            {
                this.основаниеFieldSpecified = value;
            }
        }

        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        public decimal ДоляСтавки
        {
            get
            {
                return this.доляСтавкиField;
            }
            set
            {
                this.доляСтавкиField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДоляСтавкиSpecified
        {
            get
            {
                return this.доляСтавкиFieldSpecified;
            }
            set
            {
                this.доляСтавкиFieldSpecified = value;
            }
        }
    }

    public enum ТипСтажевыйПериод2017ЛьготныйСтажВЛОснование
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-11ГР")]
        Item2711ГР,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-11ВП")]
        Item2711ВП,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-12")]
        Item2712,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-СП")]
        Item27СП,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-ПД")]
        Item27ПД,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-ПДРК")]
        Item27ПДРК,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-ГД")]
        Item27ГД,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-СМ")]
        Item27СМ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-ГДХР")]
        Item27ГДХР,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-СМХР")]
        Item27СМХР,

        /// <remarks/>
        ТВОРЧ15,

        /// <remarks/>
        ТВОРЧ20,

        /// <remarks/>
        ТВОРЧ25,

        /// <remarks/>
        ТВОРЧ30,

        /// <remarks/>
        САМОЛЕТ,

        /// <remarks/>
        СПЕЦАВ,

        /// <remarks/>
        СПАСАВ,

        /// <remarks/>
        УЧЛЕТ,

        /// <remarks/>
        ВЫСШПИЛ,

        /// <remarks/>
        НОРМАПР,

        /// <remarks/>
        НОРМСП,

        /// <remarks/>
        РЕАКТИВН,

        /// <remarks/>
        ЛЕТРАБ,

        /// <remarks/>
        ЛЕТИСП,

        /// <remarks/>
        ИТСИСП,

        /// <remarks/>
        ИТСМАВ,

        /// <remarks/>
        ИНСПЕКТ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-14")]
        Item2714,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-15")]
        Item2715,
    }

    public partial class ТипФИО
    {

        private string фамилияField;

        private string имяField;

        private string отчествоField;

        public string Фамилия
        {
            get
            {
                return this.фамилияField;
            }
            set
            {
                this.фамилияField = value;
            }
        }

        public string Имя
        {
            get
            {
                return this.имяField;
            }
            set
            {
                this.имяField = value;
            }
        }

        public string Отчество
        {
            get
            {
                return this.отчествоField;
            }
            set
            {
                this.отчествоField = value;
            }
        }
    }

    public partial class ТипСведенияДНП2017
    {

        private List<ТипСведенияДНП2017Основание> основаниеField;

        private decimal всегоШтатField;

        private string всегоФактField;

        public ТипСведенияДНП2017()
        {
            this.основаниеField = new List<ТипСведенияДНП2017Основание>();
        }

        public List<ТипСведенияДНП2017Основание> Основание
        {
            get
            {
                return this.основаниеField;
            }
            set
            {
                this.основаниеField = value;
            }
        }

        public decimal ВсегоШтат
        {
            get
            {
                return this.всегоШтатField;
            }
            set
            {
                this.всегоШтатField = value;
            }
        }

        public string ВсегоФакт
        {
            get
            {
                return this.всегоФактField;
            }
            set
            {
                this.всегоФактField = value;
            }
        }
    }

    public partial class ТипСведенияДНП2017Основание
    {

        private string подразделениеField;

        private string профессияДолжностьField;

        private decimal количествоШтатField;

        private string количествоФактField;

        private string описаниеField;

        private string документыField;

        private List<ТипСведенияДНП2017ОснованиеОУТ> оУТField;

        public ТипСведенияДНП2017Основание()
        {
            this.оУТField = new List<ТипСведенияДНП2017ОснованиеОУТ>();
        }

        public string Подразделение
        {
            get
            {
                return this.подразделениеField;
            }
            set
            {
                this.подразделениеField = value;
            }
        }

        public string ПрофессияДолжность
        {
            get
            {
                return this.профессияДолжностьField;
            }
            set
            {
                this.профессияДолжностьField = value;
            }
        }

        public decimal КоличествоШтат
        {
            get
            {
                return this.количествоШтатField;
            }
            set
            {
                this.количествоШтатField = value;
            }
        }

        public string КоличествоФакт
        {
            get
            {
                return this.количествоФактField;
            }
            set
            {
                this.количествоФактField = value;
            }
        }

        public string Описание
        {
            get
            {
                return this.описаниеField;
            }
            set
            {
                this.описаниеField = value;
            }
        }

        public string Документы
        {
            get
            {
                return this.документыField;
            }
            set
            {
                this.документыField = value;
            }
        }

        public List<ТипСведенияДНП2017ОснованиеОУТ> ОУТ
        {
            get
            {
                return this.оУТField;
            }
            set
            {
                this.оУТField = value;
            }
        }
    }

    public partial class ТипСведенияДНП2017ОснованиеОУТ
    {

        private ТипСведенияДНП2017ОснованиеОУТКод кодField;

        private string позицияСпискаField;

        public ТипСведенияДНП2017ОснованиеОУТКод Код
        {
            get
            {
                return this.кодField;
            }
            set
            {
                this.кодField = value;
            }
        }

        public string ПозицияСписка
        {
            get
            {
                return this.позицияСпискаField;
            }
            set
            {
                this.позицияСпискаField = value;
            }
        }
    }

    public enum ТипСведенияДНП2017ОснованиеОУТКод
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-1")]
        Item271,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-2")]
        Item272,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-3")]
        Item273,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-4")]
        Item274,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-5")]
        Item275,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-6")]
        Item276,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-7")]
        Item277,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-8")]
        Item278,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-9")]
        Item279,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-10")]
        Item2710,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-ОС")]
        Item27ОС,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27-ПЖ")]
        Item27ПЖ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("28-СЕВ")]
        Item28СЕВ,
    }

    public partial class ОтчетныйПериодСЗВСТАЖ
    {

        private ОтчетныйПериодСЗВСТАЖКод кодField;

        private string годField;

        public ОтчетныйПериодСЗВСТАЖ()
        {
            this.кодField = ОтчетныйПериодСЗВСТАЖКод.Item0;
        }

        public ОтчетныйПериодСЗВСТАЖКод Код
        {
            get
            {
                return this.кодField;
            }
            set
            {
                this.кодField = value;
            }
        }

        public string Год
        {
            get
            {
                return this.годField;
            }
            set
            {
                this.годField = value;
            }
        }
    }

    public enum ОтчетныйПериодСЗВСТАЖКод
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
    }

    public partial class ТипСтраховательИС
    {

        private string регНомерField;

        private string иННField;

        private string кППField;

        private string наименованиеField;

        public string РегНомер
        {
            get
            {
                return this.регНомерField;
            }
            set
            {
                this.регНомерField = value;
            }
        }

        public string ИНН
        {
            get
            {
                return this.иННField;
            }
            set
            {
                this.иННField = value;
            }
        }

        public string КПП
        {
            get
            {
                return this.кППField;
            }
            set
            {
                this.кППField = value;
            }
        }

        public string Наименование
        {
            get
            {
                return this.наименованиеField;
            }
            set
            {
                this.наименованиеField = value;
            }
        }
    }

    public partial class ТипПодразделение
    {

        private string наименованиеПодразделенияField;

        private string номерПодразделенияField;

        public string НаименованиеПодразделения
        {
            get
            {
                return this.наименованиеПодразделенияField;
            }
            set
            {
                this.наименованиеПодразделенияField = value;
            }
        }

        public string НомерПодразделения
        {
            get
            {
                return this.номерПодразделенияField;
            }
            set
            {
                this.номерПодразделенияField = value;
            }
        }
    }

    public partial class ТипИностранныйАдрес
    {

        private string кодСтраныField;

        private string названиеСтраныField;

        private string адресКириллицейField;

        private string адресЛатиницейField;

        public string КодСтраны
        {
            get
            {
                return this.кодСтраныField;
            }
            set
            {
                this.кодСтраныField = value;
            }
        }

        public string НазваниеСтраны
        {
            get
            {
                return this.названиеСтраныField;
            }
            set
            {
                this.названиеСтраныField = value;
            }
        }

        public string АдресКириллицей
        {
            get
            {
                return this.адресКириллицейField;
            }
            set
            {
                this.адресКириллицейField = value;
            }
        }

        public string АдресЛатиницей
        {
            get
            {
                return this.адресЛатиницейField;
            }
            set
            {
                this.адресЛатиницейField = value;
            }
        }
    }

    public partial class ТипНумерация
    {

        private string номерField;

        private string сокращениеField;

        public string Номер
        {
            get
            {
                return this.номерField;
            }
            set
            {
                this.номерField = value;
            }
        }

        public string Сокращение
        {
            get
            {
                return this.сокращениеField;
            }
            set
            {
                this.сокращениеField = value;
            }
        }
    }

    public partial class ТипГеография
    {

        private string названиеField;

        private string сокращениеField;

        public string Название
        {
            get
            {
                return this.названиеField;
            }
            set
            {
                this.названиеField = value;
            }
        }

        public string Сокращение
        {
            get
            {
                return this.сокращениеField;
            }
            set
            {
                this.сокращениеField = value;
            }
        }
    }

    public partial class ТипАдрес
    {

        private ТипГеография регионField;

        private ТипГеография районField;

        private ТипГеография городField;

        private ТипГеография населенныйПунктField;

        private ТипГеография улицаField;

        private ТипНумерация домField;

        private ТипНумерация строениеField;

        private ТипНумерация корпусField;

        private ТипНумерация квартираField;

        public ТипАдрес()
        {
            this.квартираField = new ТипНумерация();
            this.корпусField = new ТипНумерация();
            this.строениеField = new ТипНумерация();
            this.домField = new ТипНумерация();
            this.улицаField = new ТипГеография();
            this.населенныйПунктField = new ТипГеография();
            this.городField = new ТипГеография();
            this.районField = new ТипГеография();
            this.регионField = new ТипГеография();
        }

        public ТипГеография Регион
        {
            get
            {
                return this.регионField;
            }
            set
            {
                this.регионField = value;
            }
        }

        public ТипГеография Район
        {
            get
            {
                return this.районField;
            }
            set
            {
                this.районField = value;
            }
        }

        public ТипГеография Город
        {
            get
            {
                return this.городField;
            }
            set
            {
                this.городField = value;
            }
        }

        public ТипГеография НаселенныйПункт
        {
            get
            {
                return this.населенныйПунктField;
            }
            set
            {
                this.населенныйПунктField = value;
            }
        }

        public ТипГеография Улица
        {
            get
            {
                return this.улицаField;
            }
            set
            {
                this.улицаField = value;
            }
        }

        public ТипНумерация Дом
        {
            get
            {
                return this.домField;
            }
            set
            {
                this.домField = value;
            }
        }

        public ТипНумерация Строение
        {
            get
            {
                return this.строениеField;
            }
            set
            {
                this.строениеField = value;
            }
        }

        public ТипНумерация Корпус
        {
            get
            {
                return this.корпусField;
            }
            set
            {
                this.корпусField = value;
            }
        }

        public ТипНумерация Квартира
        {
            get
            {
                return this.квартираField;
            }
            set
            {
                this.квартираField = value;
            }
        }
    }

    public partial class ТипАдресОбщий
    {

        private string индексField;

        private object itemField;

        public string Индекс
        {
            get
            {
                return this.индексField;
            }
            set
            {
                this.индексField = value;
            }
        }

        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    public partial class ТипНН
    {

        private string иННField;

        private string кППField;

        public string ИНН
        {
            get
            {
                return this.иННField;
            }
            set
            {
                this.иННField = value;
            }
        }

        public string КПП
        {
            get
            {
                return this.кППField;
            }
            set
            {
                this.кППField = value;
            }
        }
    }

    public partial class ТипОрганизация
    {

        private ТипНН налоговыйНомерField;

        private string itemField;

        private ItemChoiceType itemElementNameField;

        private string формаField;

        private string наименованиеОрганизацииField;

        private string наименованиеКраткоеField;

        private string регистрационныйНомерField;

        private ТипАдресОбщий адресField;

        private ТипПодразделение подразделениеField;

        public ТипОрганизация()
        {
            this.подразделениеField = new ТипПодразделение();
            this.адресField = new ТипАдресОбщий();
            this.налоговыйНомерField = new ТипНН();
        }

        public ТипНН НалоговыйНомер
        {
            get
            {
                return this.налоговыйНомерField;
            }
            set
            {
                this.налоговыйНомерField = value;
            }
        }

        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }

        public string Форма
        {
            get
            {
                return this.формаField;
            }
            set
            {
                this.формаField = value;
            }
        }

        public string НаименованиеОрганизации
        {
            get
            {
                return this.наименованиеОрганизацииField;
            }
            set
            {
                this.наименованиеОрганизацииField = value;
            }
        }

        public string НаименованиеКраткое
        {
            get
            {
                return this.наименованиеКраткоеField;
            }
            set
            {
                this.наименованиеКраткоеField = value;
            }
        }

        public string РегистрационныйНомер
        {
            get
            {
                return this.регистрационныйНомерField;
            }
            set
            {
                this.регистрационныйНомерField = value;
            }
        }

        public ТипАдресОбщий Адрес
        {
            get
            {
                return this.адресField;
            }
            set
            {
                this.адресField = value;
            }
        }

        public ТипПодразделение Подразделение
        {
            get
            {
                return this.подразделениеField;
            }
            set
            {
                this.подразделениеField = value;
            }
        }
    }

    public enum ItemChoiceType
    {

        /// <remarks/>
        КодЕГРИП,

        /// <remarks/>
        КодЕГРЮЛ,
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ТипСлужебнаяИнформация1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ТипСлужебнаяИнформацияВС))]
    public partial class ТипСлужебнаяИнформация
    {

        private string gUIDField;

        private string вОтветНаField;

        private System.DateTime датаВремяField;

        public string GUID
        {
            get
            {
                return this.gUIDField;
            }
            set
            {
                this.gUIDField = value;
            }
        }

        public string ВОтветНа
        {
            get
            {
                return this.вОтветНаField;
            }
            set
            {
                this.вОтветНаField = value;
            }
        }

        public System.DateTime ДатаВремя
        {
            get
            {
                return this.датаВремяField;
            }
            set
            {
                this.датаВремяField = value;
            }
        }
    }

    public partial class ТипСлужебнаяИнформация1 : ТипСлужебнаяИнформация
    {

        private string программаПодготовкиField;

        public string ПрограммаПодготовки
        {
            get
            {
                return this.программаПодготовкиField;
            }
            set
            {
                this.программаПодготовкиField = value;
            }
        }
    }

    public partial class ТипСлужебнаяИнформацияВС : ТипСлужебнаяИнформация
    {

        private string источникДанныхField;

        private string способПередачиField;

        private ТипОрганизация составительField;

        public ТипСлужебнаяИнформацияВС()
        {
            this.составительField = new ТипОрганизация();
        }

        public string ИсточникДанных
        {
            get
            {
                return this.источникДанныхField;
            }
            set
            {
                this.источникДанныхField = value;
            }
        }

        public string СпособПередачи
        {
            get
            {
                return this.способПередачиField;
            }
            set
            {
                this.способПередачиField = value;
            }
        }

        public ТипОрганизация Составитель
        {
            get
            {
                return this.составительField;
            }
            set
            {
                this.составительField = value;
            }
        }
    }

    public partial class ObjectType
    {

        private List<System.Xml.XmlNode> anyField;

        private string idField;

        private string mimeTypeField;

        private string encodingField;

        public ObjectType()
        {
            this.anyField = new List<System.Xml.XmlNode>();
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public List<System.Xml.XmlNode> Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        public string MimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }

        public string Encoding
        {
            get
            {
                return this.encodingField;
            }
            set
            {
                this.encodingField = value;
            }
        }
    }

    public partial class SPKIDataType
    {

        private byte[][] sPKISexpField;

        private System.Xml.XmlElement anyField;

        public byte[][] SPKISexp
        {
            get
            {
                return this.sPKISexpField;
            }
            set
            {
                this.sPKISexpField = value;
            }
        }

        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    public partial class PGPDataType
    {

        private List<object> itemsField;

        private List<ItemsChoiceType1> itemsElementNameField;

        public PGPDataType()
        {
            this.itemsElementNameField = new List<ItemsChoiceType1>();
            this.itemsField = new List<object>();
        }

        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public List<ItemsChoiceType1> ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }

    public enum ItemsChoiceType1
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,

        /// <remarks/>
        PGPKeyID,

        /// <remarks/>
        PGPKeyPacket,
    }

    public partial class X509IssuerSerialType
    {

        private string x509IssuerNameField;

        private string x509SerialNumberField;

        public string X509IssuerName
        {
            get
            {
                return this.x509IssuerNameField;
            }
            set
            {
                this.x509IssuerNameField = value;
            }
        }

        public string X509SerialNumber
        {
            get
            {
                return this.x509SerialNumberField;
            }
            set
            {
                this.x509SerialNumberField = value;
            }
        }
    }

    public partial class X509DataType
    {

        private List<object> itemsField;

        private List<ItemsChoiceType> itemsElementNameField;

        public X509DataType()
        {
            this.itemsElementNameField = new List<ItemsChoiceType>();
            this.itemsField = new List<object>();
        }

        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public List<ItemsChoiceType> ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }

    public enum ItemsChoiceType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,

        /// <remarks/>
        X509CRL,

        /// <remarks/>
        X509Certificate,

        /// <remarks/>
        X509IssuerSerial,

        /// <remarks/>
        X509SKI,

        /// <remarks/>
        X509SubjectName,
    }

    public partial class RetrievalMethodType
    {

        private List<TransformType> transformsField;

        private string uRIField;

        private string typeField;

        public RetrievalMethodType()
        {
            this.transformsField = new List<TransformType>();
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable = false)]
        public List<TransformType> Transforms
        {
            get
            {
                return this.transformsField;
            }
            set
            {
                this.transformsField = value;
            }
        }

        public string URI
        {
            get
            {
                return this.uRIField;
            }
            set
            {
                this.uRIField = value;
            }
        }

        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    public partial class TransformType
    {

        private List<object> itemsField;

        private List<string> textField;

        private string algorithmField;

        public TransformType()
        {
            this.textField = new List<string>();
            this.itemsField = new List<object>();
        }

        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        public string Algorithm
        {
            get
            {
                return this.algorithmField;
            }
            set
            {
                this.algorithmField = value;
            }
        }
    }

    public partial class RSAKeyValueType
    {

        private byte[] modulusField;

        private byte[] exponentField;

        public byte[] Modulus
        {
            get
            {
                return this.modulusField;
            }
            set
            {
                this.modulusField = value;
            }
        }

        public byte[] Exponent
        {
            get
            {
                return this.exponentField;
            }
            set
            {
                this.exponentField = value;
            }
        }
    }

    public partial class DSAKeyValueType
    {

        private byte[] pField;

        private byte[] qField;

        private byte[] gField;

        private byte[] yField;

        private byte[] jField;

        private byte[] seedField;

        private byte[] pgenCounterField;

        public byte[] P
        {
            get
            {
                return this.pField;
            }
            set
            {
                this.pField = value;
            }
        }

        public byte[] Q
        {
            get
            {
                return this.qField;
            }
            set
            {
                this.qField = value;
            }
        }

        public byte[] G
        {
            get
            {
                return this.gField;
            }
            set
            {
                this.gField = value;
            }
        }

        public byte[] Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }

        public byte[] J
        {
            get
            {
                return this.jField;
            }
            set
            {
                this.jField = value;
            }
        }

        public byte[] Seed
        {
            get
            {
                return this.seedField;
            }
            set
            {
                this.seedField = value;
            }
        }

        public byte[] PgenCounter
        {
            get
            {
                return this.pgenCounterField;
            }
            set
            {
                this.pgenCounterField = value;
            }
        }
    }

    public partial class KeyValueType
    {

        private object itemField;

        private List<string> textField;

        public KeyValueType()
        {
            this.textField = new List<string>();
        }

        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    public partial class KeyInfoType
    {

        private List<object> itemsField;

        private List<ItemsChoiceType2> itemsElementNameField;

        private List<string> textField;

        private string idField;

        public KeyInfoType()
        {
            this.textField = new List<string>();
            this.itemsElementNameField = new List<ItemsChoiceType2>();
            this.itemsField = new List<object>();
        }

        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public List<ItemsChoiceType2> ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    public enum ItemsChoiceType2
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,

        /// <remarks/>
        KeyName,

        /// <remarks/>
        KeyValue,

        /// <remarks/>
        MgmtData,

        /// <remarks/>
        PGPData,

        /// <remarks/>
        RetrievalMethod,

        /// <remarks/>
        SPKIData,

        /// <remarks/>
        X509Data,
    }

    public partial class SignatureValueType
    {

        private string idField;

        private byte[] valueField;

        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute(DataType = "base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    public partial class DigestMethodType
    {

        private List<System.Xml.XmlNode> anyField;

        private string algorithmField;

        public DigestMethodType()
        {
            this.anyField = new List<System.Xml.XmlNode>();
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public List<System.Xml.XmlNode> Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        public string Algorithm
        {
            get
            {
                return this.algorithmField;
            }
            set
            {
                this.algorithmField = value;
            }
        }
    }

    public partial class ReferenceType
    {

        private List<TransformType> transformsField;

        private DigestMethodType digestMethodField;

        private byte[] digestValueField;

        private string idField;

        private string uRIField;

        private string typeField;

        public ReferenceType()
        {
            this.digestMethodField = new DigestMethodType();
            this.transformsField = new List<TransformType>();
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable = false)]
        public List<TransformType> Transforms
        {
            get
            {
                return this.transformsField;
            }
            set
            {
                this.transformsField = value;
            }
        }

        public DigestMethodType DigestMethod
        {
            get
            {
                return this.digestMethodField;
            }
            set
            {
                this.digestMethodField = value;
            }
        }

        public byte[] DigestValue
        {
            get
            {
                return this.digestValueField;
            }
            set
            {
                this.digestValueField = value;
            }
        }

        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        public string URI
        {
            get
            {
                return this.uRIField;
            }
            set
            {
                this.uRIField = value;
            }
        }

        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    public partial class SignatureMethodType
    {

        private string hMACOutputLengthField;

        private List<System.Xml.XmlNode> anyField;

        private string algorithmField;

        public SignatureMethodType()
        {
            this.anyField = new List<System.Xml.XmlNode>();
        }

        public string HMACOutputLength
        {
            get
            {
                return this.hMACOutputLengthField;
            }
            set
            {
                this.hMACOutputLengthField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public List<System.Xml.XmlNode> Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        public string Algorithm
        {
            get
            {
                return this.algorithmField;
            }
            set
            {
                this.algorithmField = value;
            }
        }
    }

    public partial class ЭДПФРОДВ1
    {

        private ЭДПФРОДВ1Тип типField;

        private ТипСтраховательИС страховательField;

        private ОтчетныйПериодСЗВСТАЖ отчетныйПериодField;

        private string количествоЗЛField;

        private List<ТипСведенияДНП2017> основанияДНПField;

        private ЭДПФРОДВ1Руководитель руководительField;

        private System.DateTime датаЗаполненияField;

        public ЭДПФРОДВ1()
        {
            this.руководительField = new ЭДПФРОДВ1Руководитель();
            this.основанияДНПField = new List<ТипСведенияДНП2017>();
            this.отчетныйПериодField = new ОтчетныйПериодСЗВСТАЖ();
            this.страховательField = new ТипСтраховательИС();
        }

        public ЭДПФРОДВ1Тип Тип
        {
            get
            {
                return this.типField;
            }
            set
            {
                this.типField = value;
            }
        }

        public ТипСтраховательИС Страхователь
        {
            get
            {
                return this.страховательField;
            }
            set
            {
                this.страховательField = value;
            }
        }

        public ОтчетныйПериодСЗВСТАЖ ОтчетныйПериод
        {
            get
            {
                return this.отчетныйПериодField;
            }
            set
            {
                this.отчетныйПериодField = value;
            }
        }

        public string КоличествоЗЛ
        {
            get
            {
                return this.количествоЗЛField;
            }
            set
            {
                this.количествоЗЛField = value;
            }
        }

        public List<ТипСведенияДНП2017> ОснованияДНП
        {
            get
            {
                return this.основанияДНПField;
            }
            set
            {
                this.основанияДНПField = value;
            }
        }

        public ЭДПФРОДВ1Руководитель Руководитель
        {
            get
            {
                return this.руководительField;
            }
            set
            {
                this.руководительField = value;
            }
        }

        public System.DateTime ДатаЗаполнения
        {
            get
            {
                return this.датаЗаполненияField;
            }
            set
            {
                this.датаЗаполненияField = value;
            }
        }
    }

    public enum ЭДПФРОДВ1Тип
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
    }

    public partial class ЭДПФРОДВ1Руководитель
    {

        private string должностьField;

        private ТипФИО фИОField;

        public ЭДПФРОДВ1Руководитель()
        {
            this.фИОField = new ТипФИО();
        }

        public string Должность
        {
            get
            {
                return this.должностьField;
            }
            set
            {
                this.должностьField = value;
            }
        }

        public ТипФИО ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }
    }

    public partial class ЭДПФРСЗВСТАЖ
    {

        private ТипСтраховательИС страховательField;

        private ЭДПФРСЗВСТАЖТип типField;

        private ОтчетныйПериодСЗВСТАЖ отчетныйПериодField;

        private List<ЭДПФРСЗВСТАЖЗЛ> злField;

        private ЭДПФРСЗВСТАЖСВ свField;

        private List<ЭДПФРСЗВСТАЖУплата> уплатаField;

        public ЭДПФРСЗВСТАЖ()
        {
            this.уплатаField = new List<ЭДПФРСЗВСТАЖУплата>();
            this.свField = new ЭДПФРСЗВСТАЖСВ();
            this.злField = new List<ЭДПФРСЗВСТАЖЗЛ>();
            this.отчетныйПериодField = new ОтчетныйПериодСЗВСТАЖ();
            this.страховательField = new ТипСтраховательИС();
        }

        public ТипСтраховательИС Страхователь
        {
            get
            {
                return this.страховательField;
            }
            set
            {
                this.страховательField = value;
            }
        }

        public ЭДПФРСЗВСТАЖТип Тип
        {
            get
            {
                return this.типField;
            }
            set
            {
                this.типField = value;
            }
        }

        public ОтчетныйПериодСЗВСТАЖ ОтчетныйПериод
        {
            get
            {
                return this.отчетныйПериодField;
            }
            set
            {
                this.отчетныйПериодField = value;
            }
        }

        public List<ЭДПФРСЗВСТАЖЗЛ> ЗЛ
        {
            get
            {
                return this.злField;
            }
            set
            {
                this.злField = value;
            }
        }

        public ЭДПФРСЗВСТАЖСВ СВ
        {
            get
            {
                return this.свField;
            }
            set
            {
                this.свField = value;
            }
        }

        public List<ЭДПФРСЗВСТАЖУплата> Уплата
        {
            get
            {
                return this.уплатаField;
            }
            set
            {
                this.уплатаField = value;
            }
        }
    }

    public enum ЭДПФРСЗВСТАЖТип
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }

    public partial class ЭДПФРСЗВСТАЖЗЛ
    {

        private ТипФИО фИОField;

        private string сНИЛСField;

        private List<ТипСтажевыйПериод2017> стажевыйПериодField;

        private System.DateTime датаУвольненияField;

        private bool датаУвольненияFieldSpecified;

        public ЭДПФРСЗВСТАЖЗЛ()
        {
            this.стажевыйПериодField = new List<ТипСтажевыйПериод2017>();
            this.фИОField = new ТипФИО();
        }

        public ТипФИО ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        public string СНИЛС
        {
            get
            {
                return this.сНИЛСField;
            }
            set
            {
                this.сНИЛСField = value;
            }
        }

        public List<ТипСтажевыйПериод2017> СтажевыйПериод
        {
            get
            {
                return this.стажевыйПериодField;
            }
            set
            {
                this.стажевыйПериодField = value;
            }
        }

        public System.DateTime ДатаУвольнения
        {
            get
            {
                return this.датаУвольненияField;
            }
            set
            {
                this.датаУвольненияField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДатаУвольненияSpecified
        {
            get
            {
                return this.датаУвольненияFieldSpecified;
            }
            set
            {
                this.датаУвольненияFieldSpecified = value;
            }
        }
    }

    public partial class ЭДПФРСЗВСТАЖСВ
    {

        private bool начисленыНаОПСField;

        private bool начисленыНаОПСFieldSpecified;

        private bool начисленыПоДТField;

        private bool начисленыПоДТFieldSpecified;

        public bool НачисленыНаОПС
        {
            get
            {
                return this.начисленыНаОПСField;
            }
            set
            {
                this.начисленыНаОПСField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool НачисленыНаОПСSpecified
        {
            get
            {
                return this.начисленыНаОПСFieldSpecified;
            }
            set
            {
                this.начисленыНаОПСFieldSpecified = value;
            }
        }

        public bool НачисленыПоДТ
        {
            get
            {
                return this.начисленыПоДТField;
            }
            set
            {
                this.начисленыПоДТField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool НачисленыПоДТSpecified
        {
            get
            {
                return this.начисленыПоДТFieldSpecified;
            }
            set
            {
                this.начисленыПоДТFieldSpecified = value;
            }
        }
    }

    public partial class ЭДПФРСЗВСТАЖУплата
    {

        private ТипВременнойПериод периодField;

        private bool уплаченоField;

        public ЭДПФРСЗВСТАЖУплата()
        {
            this.периодField = new ТипВременнойПериод();
        }

        public ТипВременнойПериод Период
        {
            get
            {
                return this.периодField;
            }
            set
            {
                this.периодField = value;
            }
        }

        public bool Уплачено
        {
            get
            {
                return this.уплаченоField;
            }
            set
            {
                this.уплаченоField = value;
            }
        }
    }
}
